# Generated by Django 3.2 on 2021-04-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
