# Generated by Django 3.2 on 2021-04-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_prdcreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDCreated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created At'),
        ),
    ]
