# Generated by Django 3.1.7 on 2021-04-28 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerproduct',
            name='OwnerQuantity',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
