# Generated by Django 3.2 on 2021-04-06 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_prdcreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDCreated',
        ),
        migrations.AddField(
            model_name='product',
            name='PRDCreatedNow',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created in'),
            preserve_default=False,
        ),
    ]
