# Generated by Django 3.2 on 2021-04-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
