# Generated by Django 3.1.7 on 2021-04-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order'),
        ('product', '0005_auto_20210407_1424'),
    ]

    operations = [
    ]
