# Generated by Django 3.2 on 2021-04-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210407_1424'),
        ('product', '0007_order'),
    ]

    operations = [
    ]
