# Generated by Django 3.1.7 on 2021-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_merge_20210409_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDCost',
            field=models.FloatField(verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDiscountPrice',
            field=models.FloatField(verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
