# Generated by Django 3.1.7 on 2021-04-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210409_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Orderuser',
        ),
    ]
