# Generated by Django 3.2 on 2021-04-11 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.rating', verbose_name='PRDRate'),
        ),
    ]
