# Generated by Django 3.1.7 on 2021-04-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_order_orderuser'),
        ('product', '0011_product_prdrate'),
    ]

    operations = [
    ]
