# Generated by Django 3.2 on 2021-04-14 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_product_prdrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerQuantity', models.IntegerField(verbose_name=product.models.Product)),
                ('OwnerProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='OwnerProduct')),
                ('OwnerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OwnerUser')),
            ],
        ),
    ]
