# Generated by Django 3.2 on 2021-04-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_ownerproduct'),
        ('product', '0013_auto_20210414_1457'),
    ]

    operations = [
    ]
