# Generated by Django 3.2 on 2021-04-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210417_1652'),
        ('product', '0015_auto_20210416_2301'),
    ]

    operations = [
    ]
