# Generated by Django 3.2 on 2021-04-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210418_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerproduct',
            name='Ownerproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='product.product', verbose_name='OwnerProduct'),
        ),
    ]
