# Generated by Django 3.2 on 2021-04-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_ownerproduct_ownerquantity'),
        ('product', '0018_alter_ownerproduct_ownerproduct'),
    ]

    operations = [
    ]
