# Generated by Django 3.2 on 2021-04-19 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_ownerproduct_ownerproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerproduct',
            name='OwnerQuantity',
        ),
        migrations.AddField(
            model_name='product',
            name='PRDQuantity',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
