# Generated by Django 3.2 on 2021-04-19 19:08

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210419_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_path, verbose_name='Image'),
        ),
    ]
