# Generated by Django 3.2 on 2021-04-19 22:50

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_prdimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDRate',
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.nameFile, verbose_name='Image'),
        ),
    ]
